services:
  php:
    image: php:8.3-fpm
    container_name: php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - TZ=America/Sao_Paulo
    restart: always

    # ===== LIMITES DE RECURSOS =====
    mem_limit: 512m
    memswap_limit: 512m
    cpus: 1.50
    cpu_shares: 1024
    cpuset: "0-2"

    ulimits:
      nproc: 4096
      nofile:
        soft: 8192
        hard: 8192

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    depends_on:
      - php

    # ===== LIMITES DE RECURSOS =====
    mem_limit: 256m
    memswap_limit: 256m
    cpus: 0.50
    cpu_shares: 512
    cpuset: "0-2"

    ulimits:
      nproc: 2048
      nofile:
        soft: 8192
        hard: 8192
